# Generated by Django 2.1.1 on 2019-01-20 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='城市')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市名称',
                'verbose_name_plural': '城市名称',
            },
        ),
        migrations.CreateModel(
            name='MarketActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='活动标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('category_ticket', models.CharField(choices=[('ssq', '双色球'), ('dz', '动物总动员'), ('3d', '3D'), ('qlc', '七乐彩'), ('jkp', '即开票')], default='dz', max_length=10, verbose_name='活动票种')),
                ('category_person', models.CharField(choices=[('1', '业主'), ('2', '彩民'), ('3', '彩民和业主')], default='1', max_length=10, verbose_name='针对人群')),
                ('content', models.TextField(verbose_name='具体内容')),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('click_stars', models.IntegerField(default=0, verbose_name='点赞数')),
                ('image', models.ImageField(default='org/default.png', upload_to='org/%Y/%m', verbose_name='Logo')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '营销活动',
                'verbose_name_plural': '营销活动',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='marketactivity',
            name='tag',
            field=models.ManyToManyField(related_name='market_tag', to='market.Tag', verbose_name='标签'),
        ),
    ]
